routes/web.php
<?php

use App\Http\Controllers\InscriptionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('profile.show');
})->name('dashboard');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('tasks', \App\Http\Controllers\TasksController::class);

    Route::resource('users', \App\Http\Controllers\UsersController::class);

    Route::resource('inscriptions', InscriptionController::class);
});

app/Models/Inscription.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Inscription extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'domaine_id',
        'status',
        'motivation'
    ];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function domaine(){
        return $this->belongsTo(Domaine::class);
    }
}

app/Http/Controllers/InscriptionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreInscriptionRequest;
use App\Http\Requests\UpdateInscriptionRequest;
use App\Models\Domaine;
use App\Models\Inscription;
use App\Models\User;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Symfony\Component\HttpFoundation\Response;

class InscriptionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        abort_if(Gate::denies('task_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $role = User::find(Auth::user()->id)->roles[0]->title;
        $user = User::find(Auth::user()->id);
        $inscriptions = $user->inscriptions;
        if ($role == 'Admin') {
            $inscriptions = Inscription::all();
        }


        return view('inscriptions.index', compact('inscriptions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $role = User::find(Auth::user()->id)->roles[0]->title;
        abort_if(Gate::denies('task_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $domaines = Domaine::pluck('title', 'id');
        $users = User::pluck('name', 'id');
        return view('inscriptions.create', compact('domaines', 'role', 'users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreInscriptionRequest $request)
    {
        try {
            DB::beginTransaction();
            $role = User::find(Auth::user()->id)->roles[0]->title;

            $inscription = Inscription::create($request->validated());

            if ($role != 'Admin') {

                $inscription->status = 2;

                $inscription->save();
            }
            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
            echo 'Message: ' . $e->getMessage();
        }




        //DB::rollBack();

        return redirect()->route('inscriptions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Inscription $inscription)
    {
        abort_if(Gate::denies('task_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('inscriptions.show', compact('inscription'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Inscription $inscription)
    {
        abort_if(Gate::denies('task_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $domaines = Domaine::pluck('title', 'id');

        $role = User::find(Auth::user()->id)->roles[0]->title;

        $users = User::pluck('name', 'id');

        return view('inscriptions.edit', compact('inscription', 'domaines', 'role', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateInscriptionRequest $request, Inscription $inscription)
    {
        // DB::transaction(function () {
        //     DB::update('update inscriptions set votes = 1');
        //     // DB::delete('delete from posts');
        //     DB::table('inscriptions')->where('id', $inscription->id)


        // }, 5);
        DB::transaction(function () use ($inscription, $request) {
            $inscription->update($request->validated());
        }, 5);


        return redirect()->route('inscriptions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Inscription $inscription)
    {
        abort_if(Gate::denies('task_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $inscription->delete();

        return redirect()->route('inscriptions.index');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/inscriptions/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex-row justify-content-between" style="display: flex; justify-content: space-between;" >
            <div class="col-md-6">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                    S'inscrire
                </h2>

            </div>
            <div class="col-md-6">
                <a href="{{ route('inscriptions.index') }}" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">
                    Mes inscriptions
                </a>
            </div>
        </div>
    </x-slot>

    <div>
        <div class="max-w-4xl mx-auto py-10 sm:px-6 lg:px-8">
            <div class="mt-5 md:mt-0 md:col-span-2">
                <form method="post" action="{{ route('inscriptions.store') }}">
                    @csrf
                    <div class="shadow overflow-hidden sm:rounded-md">
                        @if ( $role == 'Admin')
                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="users" class="block font-medium text-sm text-gray-700">Lauréat <span class="text-red-800">*</span></label>
                            <select name="user_id" id="users" class="form-multiselect block rounded-md shadow-sm mt-1 block w-full">
                                <option value=""></option>
                                @foreach($users as $id => $user)
                                    <option value="{{ $id }}">{{ $user }}</option>
                                @endforeach
                            </select>
                            @error('user_id')
                                <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>
                        @else
                            <input type="text" name="user_id" value="{{Auth::user()->id}}" hidden>
                        @endif
                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="domaines" class="block font-medium text-sm text-gray-700">Domaine <span class="text-red-800">*</span></label>
                            <select name="domaine_id" id="domaines" class="form-multiselect block rounded-md shadow-sm mt-1 block w-full">
                                <option value=""></option>
                                @foreach($domaines as $id => $domaine)
                                    <option value="{{ $id }}"{{ in_array($id, old('domaines', [])) ? ' selected' : '' }}>{{ $domaine }}</option>
                                @endforeach
                            </select>
                            @error('domaine_id')
                                <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="motivation" class="block font-medium text-sm text-gray-700">Votre motivation</label>
                            <textarea name="motivation" id="motivation" cols="30" rows="6" class="form-input rounded-md shadow-sm mt-1 block w-full">
                                {{ old('motivation', '') }}
                            </textarea>
                            @error('motivation')
                                <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>
                        @if ( $role == 'Admin')
                            <div class="px-4 py-5 bg-white sm:p-6">
                                <label for="status" class="block font-medium text-sm text-gray-700">Statut</label>
                                <select name="status" id="status" class="form-multiselect block rounded-md shadow-sm mt-1 block w-full">
                                    <option value="1">Approuvé</option>
                                    <option value="2">En attente</option>
                                    <option value="0">Rejeté</option>
                                </select>
                                @error('status')
                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                @enderror
                            </div>
                        @endif



                        <div class="flex items-center justify-end px-4 py-3 bg-gray-50 text-right sm:px-6">
                            <button class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">
                                S'inscrire maintenant
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/inscriptions/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Modifier
        </h2>
    </x-slot>

    <div>
        <div class="max-w-4xl mx-auto py-10 sm:px-6 lg:px-8">
            <div class="mt-5 md:mt-0 md:col-span-2">
                <form method="post" action="{{ route('inscriptions.update', $inscription->id) }}">
                    @csrf
                    @method('PUT')
                    <div class="shadow overflow-hidden sm:rounded-md">
                        @if ($role == 'Admin')
                            <div class="px-4 py-5 bg-white sm:p-6">
                                <label for="users" class="block font-medium text-sm text-gray-700">Lauréat <span
                                        class="text-red-800">*</span></label>
                                <select name="user_id" id="users"
                                    class="form-multiselect block rounded-md shadow-sm mt-1 block w-full">
                                    @foreach ($users as $id => $user)
                                        <option value="{{ $id }}" {{ $id == $inscription->user->id ? 'selected' : '' }}>{{ $user }}</option>
                                    @endforeach
                                </select>
                                @error('user_id')
                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                @enderror
                            </div>
                        @endif
                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="domaines" class="block font-medium text-sm text-gray-700">Domaine</label>
                            <select name="domaine_id" id="domaines"
                                class="form-multiselect block rounded-md shadow-sm mt-1 block w-full">
                                @foreach ($domaines as $id => $domaine)
                                    <option value="{{ $id }}"
                                        {{ $id == $inscription->domaine->id ? ' selected' : '' }}>
                                        {{ $domaine }}</option>
                                @endforeach
                            </select>
                            @error('domaine_id')
                                <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="motivation" class="block font-medium text-sm text-gray-700">Motivation</label>
                            <input type="text" name="motivation" id="motivation" type="text"
                                class="form-input rounded-md shadow-sm mt-1 block w-full"
                                value="{{ old('motivation', $inscription->motivation) }}" />
                            @error('motivation')
                                <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        @if ( $role == 'Admin')
                            <div class="px-4 py-5 bg-white sm:p-6">
                                <label for="status" class="block font-medium text-sm text-gray-700">Statut</label>
                                <select name="status" id="status" class="form-multiselect block rounded-md shadow-sm mt-1 block w-full">
                                    <option {{$inscription->status == 1 ? 'selected' : ''}} value="1">Approuvé</option>
                                    <option {{$inscription->status == 2 ? 'selected' : ''}} value="2">En attente</option>
                                    <option {{$inscription->status == 0 ? 'selected' : ''}} value="0">Rejeté</option>
                                </select>
                                @error('status')
                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                @enderror
                            </div>
                        @endif



                        <div class="flex items-center justify-end px-4 py-3 bg-gray-50 text-right sm:px-6">
                            <button
                                class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">
                                Mettre à jour
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/inscriptions/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Toutes les inscriptions
        </h2>
    </x-slot>

    <div>
        <div class="max-w-6xl mx-auto py-10 sm:px-6 lg:px-8">
            <div class="block mb-8">
                <a href="{{ route('inscriptions.create') }}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Nouvelle inscription</a>
            </div>
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200 w-full">
                                <thead>
                                <tr>
                                    <th scope="col" width="50" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        ID
                                    </th>
                                    <th scope="col" width="50" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Lauréat
                                    </th>
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Domaine
                                    </th>
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Motivation
                                    </th>
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Status
                                    </th>
                                    <th scope="col" width="200" class="px-6 py-3 bg-gray-50">

                                    </th>
                                </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                @foreach ($inscriptions as $inscription)
                                    <tr>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                            {{ $inscription->id }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                            @if (Auth::user()->id == $inscription->user->id)
                                                Vous ( {{ $inscription->user->name }} )
                                            @else
                                                {{ $inscription->user->name }}
                                            @endif

                                        </td>

                                         <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                            {{ $inscription->domaine->title }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                            {{ $inscription->motivation }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                            @if ( $inscription->status == 1)
                                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                                    Approuvé
                                                </span>
                                            @endif
                                            @if ( $inscription->status == 0)
                                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                                    Rejeté
                                                </span>
                                            @endif
                                            @if ( $inscription->status == 2)
                                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-orange-100 text-orange-800">
                                                    En attente
                                                </span>
                                            @endif

                                        </td>


                                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                                            <a href="{{ route('inscriptions.show', $inscription->id) }}" class="text-blue-600 hover:text-blue-900 mb-2 mr-2">Voir</a>
                                            <a href="{{ route('inscriptions.edit', $inscription->id) }}" class="text-indigo-600 hover:text-indigo-900 mb-2 mr-2">Modifier</a>
                                            <form class="inline-block" action="{{ route('inscriptions.destroy', $inscription->id) }}" method="POST" onsubmit="return confirm('Etes vous sur?');">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <input type="submit" class="text-red-600 hover:text-red-900 mb-2 mr-2" value="Supprimer">
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</x-app-layout>

resources/views/inscriptions/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Voir l'inscription
        </h2>
    </x-slot>

    <div>
        <div class="max-w-6xl mx-auto py-10 sm:px-6 lg:px-8">
            <div class="block mb-8">
                <a href="{{ route('inscriptions.index') }}" class="bg-gray-200 hover:bg-gray-300 text-black font-bold py-2 px-4 rounded">Retourner à la liste</a>
            </div>
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200 w-full">
                                <tr class="border-b">
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        ID
                                    </th>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 bg-white divide-y divide-gray-200">
                                        {{ $inscription->id }}
                                    </td>
                                </tr>
                                <tr class="border-b">
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Lauréat
                                    </th>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 bg-white divide-y divide-gray-200">
                                        @if (Auth::user()->id == $inscription->user->id)
                                            Vous ( {{ $inscription->user->name }} )
                                        @else
                                            {{ $inscription->user->name }}
                                        @endif
                                    </td>
                                </tr>
                                <tr class="border-b">
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Domaine
                                    </th>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 bg-white divide-y divide-gray-200">
                                        {{ $inscription->domaine->title }}
                                    </td>
                                </tr>
                                <tr class="border-b">
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Motivation
                                    </th>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 bg-white divide-y divide-gray-200">
                                        {{ $inscription->motivation }}
                                    </td>
                                </tr>
                                <tr class="border-b">
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Statut
                                    </th>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 bg-white divide-y divide-gray-200">
                                        @if ( $inscription->status == 1)
                                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                                Approuvé
                                            </span>
                                        @endif
                                        @if ( $inscription->status == 0)
                                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                                Rejeté
                                            </span>
                                        @endif
                                        @if ( $inscription->status == 2)
                                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-orange-100 text-orange-800">
                                                En attente
                                            </span>
                                        @endif
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="block mt-8">
                <a href="{{ route('inscriptions.index') }}" class="bg-gray-200 hover:bg-gray-300 text-black font-bold py-2 px-4 rounded">Retourner à la liste</a>
            </div>
        </div>
    </div>
</x-app-layout>